FROM golang:1.21 AS builder
WORKDIR /app

COPY . .

RUN go build -o frontend ./app/frontend

FROM gcr.io/distroless/base
COPY --from=builder /app/frontend /frontend

EXPOSE 8080
ENTRYPOINT ["/frontend"]
